### ISSUE TITLE
Erro ou faltou alguma coisa?

### ISSUE THREAD

**Issue by terroo** [lucasfturos/QuebrandoBloquinho#1]
Opa, Lucas! Tô estudando Zig e tentei compilar seu projeto e apresentou essa falha:

![08-10-17-25-05-2023](https://github.com/lucasfturos/QuebrandoBloquinho/assets/41500739/7d7d5201-4af2-4787-a1a1-9738c01465e9)

**Comment by lucasfturos** [comment]
> Opa, Lucas! Tô estudando Zig e tentei compilar seu projeto e apresentou essa falha:
> 
> ![08-10-17-25-05-2023](https://user-images.githubusercontent.com/41500739/240894650-7d7d5201-4af2-4787-a1a1-9738c01465e9.png)

Opa, Marcelo, beleza. Também estou estudando Zig.
Que estranho esse erro. 
Eu estou usando o binário da versão mais recente do Zig para compilar o programa, testa para ver se esse erro resolve assim. Ele ta disponível no site:
```
https://ziglang.org/download/
https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.3298+5744ceedb.tar.xz
```
Depois de baixar ficaria assim com o uso do binário:
```
../zig-linux-x86_64-0.11.0-dev.3298+5744ceedb/zig build run
ou
../zig/zig build run
```
Se for erro de versão, é para funcionar ao executar o comando como acima. Mas se quiser tentar com o que já tem instalado, tem esse exemplo em SDL no Zig. Ai usa o build.zig desse repo:
```
https://github.com/andrewrk/sdl-zig-demo
```

**Comment by terroo** [comment]
Opa, blz então! Vou tentar aqui uma nova versão. Valeu!
